# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created: Thu Apr 28 12:18:14 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import DB_manager,sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.dbu = DB_manager.DatabaseUtility()
        self.setupUi(self)
        
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(676, 434)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 701, 431))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(210, 0, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(230, 100, 101, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 140, 101, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 81, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 191, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(230, 190, 101, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(80, 250, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 250, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(230, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(80, 50, 471, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(250, 130, 141, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(150, 130, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(90, 190, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.radioButton = QtGui.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(230, 190, 161, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(430, 190, 141, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 250, 171, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(0, 40, 601, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(0, 160, 601, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.textBrowser = QtGui.QTextBrowser(Form)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(30, 320, 541, 91))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "S.A.V.E", None))
        self.label_2.setText(_translate("Form", "Save Ambient Volume Efficiently", None))
        self.comboBox.setItemText(0, _translate("Form", "---Select City---", None))
        self.comboBox.setItemText(1, _translate("Form", "Allahabad", None))
        self.comboBox.setItemText(2, _translate("Form", "Chennai", None))
        self.comboBox.setItemText(3, _translate("Form", "Delhi", None))
        self.comboBox.setItemText(4, _translate("Form", "Ghaziabad", None))
        self.comboBox.setItemText(5, _translate("Form", "Kolkatta", None))
        self.comboBox_2.setItemText(0, _translate("Form", "----Select Year----", None))
        self.comboBox_2.setItemText(1, _translate("Form", "2015", None))
        self.comboBox_2.setItemText(2, _translate("Form", "2016", None))
        self.comboBox_2.setItemText(3, _translate("Form", "2017", None))
        self.comboBox_2.setItemText(4, _translate("Form", "2018", None))
        self.label_4.setText(_translate("Form", "Select Year", None))
        self.label_5.setText(_translate("Form", "Enter house area (sq. ft) ", None))
        self.pushButton.setText(_translate("Form", "Calculate", None))
        self.pushButton_2.setText(_translate("Form", "Reset", None))
        self.label_3.setText(_translate("Form", "Select City", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Main", None))
        self.label_6.setText(_translate("Form", "Analysis", None))
        self.label_7.setText(_translate("Form", "<html><head/><body><p>Here we are using Multiple linear Regression Machine Learning Model</p></body></html>", None))
        self.comboBox_3.setItemText(0, _translate("Form", "-----Select City ------", None))
        self.comboBox_3.setItemText(1, _translate("Form", "Allahabad", None))
        self.comboBox_3.setItemText(2, _translate("Form", "Chennai", None))
        self.comboBox_3.setItemText(3, _translate("Form", "Kolkata", None))
        self.comboBox_3.setItemText(4, _translate("Form", "Delhi", None))
        self.comboBox_3.setItemText(5, _translate("Form", "Ghaziabad", None))
        self.label_8.setText(_translate("Form", "Select City", None))
        self.label_9.setText(_translate("Form", "Get Analysis By", None))
        self.radioButton.setText(_translate("Form", "Monsoon Rainfall Analysis ", None))
        self.radioButton_2.setText(_translate("Form", "Annual Rainfall Analysis ", None))
        self.pushButton_3.setText(_translate("Form", "Show Result ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Auxiliary", None))
    
    @QtCore.pyqtSignature("on_pushButton_clicked()")
    def commmit(self):
        
        state = str(self.comboBox.currentText())
        year = float(self.comboBox_2.currentText())
        area = float(self.lineEdit.text())
        value = int(self.dbu.Calculation(state, year, area))
        Electricity = int((value/3600)*746)
        cfl = "You can light %d CFL's using the electricity saved"%(int(Electricity/40))
        self.textBrowser.setText("You will save upto " + str(value) + " ltrs of water" + "\n" + "You will save " + str(Electricity) + " watt of energy" + "\n" + cfl)
        
    
    @QtCore.pyqtSignature("on_pushButton_2_clicked()")
    def reset(self):
        self.textBrowser.setText(" ")
        self.lineEdit.setText(" ")
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
    
    @QtCore.pyqtSignature("on_pushButton_3_clicked()")
    def analysis(self):
        if(self.radioButton.isChecked()):
            state = str(self.comboBox_3.currentText())
            x = self.dbu.ShowAnalysis(state,1)
            self.textBrowser.setText("Mean Absolute error: " + str(x[1]) + "\n" + "Mean Squared Error: "+ str(x[2]) + "\n" + " Root Mean Squared Error : "+ str(x[3])+ "\n" + "Median Absolute Error : "+ str(x[4])+ "\n" + "R2 Score (Coefficient of determination): " + str(x[5]))
    
        else:
            state = str(self.comboBox_3.currentText())
            x = self.dbu.ShowAnalysis(state,0)  
            self.textBrowser.setText("Mean Absolute error: " + str(x[1]) + "\n" + "Mean Squared Error: "+ str(x[2]) + "\n" + " Root Mean Squared Error : "+ str(x[3])+ "\n" + "Median Absolute Error : "+ str(x[4])+ "\n" + "R2 Score (Coefficient of determination): " + str(x[5]))
    
if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    window = Ui_Form()
    window.show()
    sys.exit(app.exec_())